// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2MrI9O7ik0006ZbjjWvE7Ffynj1bVMck',
    appId: '1:957127422199:web:826bfd6c4fefdee09363f2',
    messagingSenderId: '957127422199',
    projectId: 'myclassroom-5fd5c',
    authDomain: 'myclassroom-5fd5c.firebaseapp.com',
    storageBucket: 'myclassroom-5fd5c.firebasestorage.app',
    measurementId: 'G-R14YTZEQ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCejYFwvdvSSdXLCyLwp_O7N7NeAX50fQc',
    appId: '1:957127422199:android:2574b06c2bb612729363f2',
    messagingSenderId: '957127422199',
    projectId: 'myclassroom-5fd5c',
    storageBucket: 'myclassroom-5fd5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1AaS-8NrS4GtriX8dlDxTo64lst_5RjI',
    appId: '1:957127422199:ios:6156d1833f69ab779363f2',
    messagingSenderId: '957127422199',
    projectId: 'myclassroom-5fd5c',
    storageBucket: 'myclassroom-5fd5c.firebasestorage.app',
    iosBundleId: 'prem.dev.myclassroom.myclassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1AaS-8NrS4GtriX8dlDxTo64lst_5RjI',
    appId: '1:957127422199:ios:6156d1833f69ab779363f2',
    messagingSenderId: '957127422199',
    projectId: 'myclassroom-5fd5c',
    storageBucket: 'myclassroom-5fd5c.firebasestorage.app',
    iosBundleId: 'prem.dev.myclassroom.myclassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2MrI9O7ik0006ZbjjWvE7Ffynj1bVMck',
    appId: '1:957127422199:web:c9d2e0ce52858c4a9363f2',
    messagingSenderId: '957127422199',
    projectId: 'myclassroom-5fd5c',
    authDomain: 'myclassroom-5fd5c.firebaseapp.com',
    storageBucket: 'myclassroom-5fd5c.firebasestorage.app',
    measurementId: 'G-NCT4KJRTBB',
  );
}
