// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB-CxNN2Tb1EdEWixrJsj83r2gchbH2eg',
    appId: '1:1062358116698:web:95859c7330b8e94c9e2b63',
    messagingSenderId: '1062358116698',
    projectId: 'myclassroom-3996f',
    authDomain: 'myclassroom-3996f.firebaseapp.com',
    storageBucket: 'myclassroom-3996f.firebasestorage.app',
    measurementId: 'G-J3R5V0P49F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyWZOeT1a9AgsGmr74FgUt2pi7BWNQGvQ',
    appId: '1:1062358116698:android:ccef84d9f77220269e2b63',
    messagingSenderId: '1062358116698',
    projectId: 'myclassroom-3996f',
    storageBucket: 'myclassroom-3996f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHr71CbvyBrwMohv3TV67TeizTfkrGjIQ',
    appId: '1:1062358116698:ios:4176b88427980f289e2b63',
    messagingSenderId: '1062358116698',
    projectId: 'myclassroom-3996f',
    storageBucket: 'myclassroom-3996f.firebasestorage.app',
    iosBundleId: 'prem.dev.parikshamadadkendra.parikshamadadkendra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHr71CbvyBrwMohv3TV67TeizTfkrGjIQ',
    appId: '1:1062358116698:ios:4176b88427980f289e2b63',
    messagingSenderId: '1062358116698',
    projectId: 'myclassroom-3996f',
    storageBucket: 'myclassroom-3996f.firebasestorage.app',
    iosBundleId: 'prem.dev.parikshamadadkendra.parikshamadadkendra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB-CxNN2Tb1EdEWixrJsj83r2gchbH2eg',
    appId: '1:1062358116698:web:a3149e0897c299c19e2b63',
    messagingSenderId: '1062358116698',
    projectId: 'myclassroom-3996f',
    authDomain: 'myclassroom-3996f.firebaseapp.com',
    storageBucket: 'myclassroom-3996f.firebasestorage.app',
    measurementId: 'G-Y0Y1RV8C1X',
  );
}
